{{- if .Values.storageClass.create -}}
{{- range .Values.storageClass.classes }}
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .name }}
  labels:
    {{- include "kubernetes-zfs-provisioner.labels" $ | nindent 4 }}
{{- with .annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
{{- end }}
provisioner: {{ $.Values.provisioner.instance }}
{{- if eq .type "auto" }}
volumeBindingMode: WaitForFirstConsumer
{{- end }}
reclaimPolicy: {{ .policy | default "Delete" }}
parameters:
  parentDataset: {{ .parentDataset }}
  hostname: {{ .hostName }}
  type: {{ .type | default "nfs" }}
  node: {{ .node | default "''" }}
  shareProperties: {{ .shareProperties | default "''" }}
  {{- if kindIs "bool" .reserveSpace }}
  reserveSpace: {{ quote .reserveSpace }}
  {{- end }}
{{- end }}
{{- end }}
