name: ChartLint

on:
  pull_request:
    # only run when there are chart changes
    paths:
      - 'charts/**'
      - '!charts/charts.mk'
      - '!charts/go*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: charts/go.mod

      - name: Verify charts are upt-do-date
        run: make chart-lint

  template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Render Helm charts
        run: find charts -type f -name Chart.yaml -exec .github/render-charts.sh {} \;
