name: ChartTest

on:
  pull_request:
    # only run when there are chart changes
    paths:
      - 'charts/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version-file: charts/go.mod

      - name: Run chart tests
        run: make chart-test
