name: Test

on:
  push:
    branches:
      - master
    tags-ignore:
      - "*"
    paths-ignore:
      - charts/**
      - docs/**
  pull_request:
    branches:
      - master
    paths-ignore:
      - charts/**
      - docs/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Run unit tests
        run: make test

      - name: Run integration tests
        run: make install:zfs test:integration
